version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: food_delivery_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vishal@90
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vishal@90
    depends_on:
      - mysql-db

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: food_delivery_api_gateway
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - JWT_SECRET=12345678901234567890123456789012
      - NOTIFICATION_SERVICE_URL=http://notification-service:8085
    depends_on:
      - auth-service

  restaurant-service:
    build:
      context: ./restaurent-service
      dockerfile: Dockerfile
    image: vishalsharma/restaurant-service:latest
    container_name: restaurant_service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vishal@90
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mysql-db
      - kafka

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: vishalsharma/order-service:latest
    container_name: order_service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vishal@90
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8082
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mysql-db
      - restaurant-service
      - kafka

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    image: vishalsharma/payment-service:latest
    container_name: payment_service
    restart: on-failure
    ports:
      - "8084:8084"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vishal@90
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mysql-db
      - kafka

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: vishalsharma/notification-service:latest
    container_name: notification_service
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vishal@90
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mysql-db
      - kafka

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: food_delivery_zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami

  kafka:
    image: bitnami/kafka:latest
    container_name: food_delivery_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami

volumes:
  mysql_data:
  zookeeper_data:
  kafka_data:
