apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Kubernetes can handle base64 encoding for you if you use stringData
  mysql-root-password: "Vishal@90"
  jwt-secret: "12345678901234567890123456789012"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Shared configuration variables across your microservices
  MYSQL_HOST: "mysql-db"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8081"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
  USER_SERVICE_URL: "http://user-service:8086"
